import './scss/styles.scss';
import './js/loader.js';
import './servises/productsApi.js';
import './js/social-media.js';
import './js/choice.js';
import './js/products.js';
import './js/modal/modal.js';
import './js/modal/modal-end.js';
import './js/slider.js';
